#!/usr/bin/env python3
"""Generate derived CCWM navigation indexes."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterable, List

from ccwm_common import (
    ccwm_path,
    first_narrative_sentence,
    next_decision,
    parse_runs,
    point_summary,
    quoted,
    read_text,
    sentence_from,
    shorten,
    write_if_changed,
    yaml_scalar,
)


def build_run_index(log_text: str) -> str:
    runs = parse_runs(log_text)
    lines: List[str] = [
        "# CCWM Run Index",
        "",
        "Generated by `docs/CCWM/tools/ccwm_index.py`. Do not hand-edit.",
        "",
        "| Run | Line | Title | Location | Action | Friction | Next Decision |",
        "| --- | ---: | --- | --- | --- | --- | --- |",
    ]

    friction_keywords = [
        "blocked",
        "gate",
        "gold",
        "no ",
        "not ",
        "cannot",
        "missing",
        "risk",
        "requires",
        "nothing",
        "failed",
    ]

    for entry in runs:
        action = first_narrative_sentence(entry.body)
        friction = sentence_from(entry.body, friction_keywords)
        decision = next_decision(entry.body)
        location = point_summary(entry.body)

        lines.append(
            "| {0} | {1} | {2} | {3} | {4} | {5} | {6} |".format(
                entry.number,
                entry.line,
                shorten(entry.title, 70),
                shorten(location or "unknown", 45),
                shorten(action or "see log", 140),
                shorten(friction or "none recorded", 120),
                shorten(decision or "see next run", 140),
            )
        )

    lines.append("")
    return "\n".join(lines)


def list_item(lines: List[str], indent: int, value: str) -> None:
    lines.append("{0}- {1}".format(" " * indent, value))


def bool_from_state(state_text: str, key: str) -> str:
    match = re.search(r"{0}:\s*(true|false)".format(re.escape(key)), state_text)
    return match.group(1) if match else "unknown"


def build_knowledge_index(log_text: str, state_text: str) -> str:
    runs = parse_runs(log_text)
    latest_run = runs[-1].number if runs else 0
    current_goal = yaml_scalar(state_text, ("lifecycle", "current_goal")) or ""
    next_action = yaml_scalar(state_text, ("lifecycle", "next_client_visible_decision")) or ""
    region = yaml_scalar(state_text, ("location", "region_name")) or ""
    stage = yaml_scalar(state_text, ("lifecycle", "stage")) or ""

    active_leads: List[str] = []
    if "Moria" in next_action:
        active_leads.append("Inspect Moria as a nearby passive citizen lead.")
    if "Van" in next_action:
        active_leads.append("Inspect Van as a nearby passive citizen lead.")
    if "Paulin" in next_action:
        active_leads.append("Inspect Paulin only as guard/town context, not as a theft route.")
    if "shop cluster" in next_action:
        active_leads.append("Route east toward the known Britain shop cluster.")
    if "Bank of Britain" in next_action:
        active_leads.append("Route north/east toward the Bank of Britain marker.")

    if not active_leads and next_action:
        active_leads.append(next_action)

    lines: List[str] = [
        "# Generated by docs/CCWM/tools/ccwm_index.py. Do not hand-edit.",
        "metadata:",
        "  source_log: \"docs/CCWM/Confictura_Codex_World_Map.md\"",
        "  source_state: \"docs/CCWM/Simulation_State.yaml\"",
        "  latest_run: {0}".format(latest_run),
        "  deterministic: true",
        "",
        "current_state:",
        "  stage: {0}".format(quoted(stage)),
        "  region: {0}".format(quoted(region)),
        "  current_goal: {0}".format(quoted(current_goal)),
        "  next_client_visible_decision: {0}".format(quoted(next_action)),
        "",
        "discovered_worlds:",
        "  sosaria: {0}".format(bool_from_state(state_text, "land_of_sosaria")),
        "  lodoria: {0}".format(bool_from_state(state_text, "land_of_lodoria")),
        "  savaged_empire: {0}".format(bool_from_state(state_text, "savaged_empire")),
        "  ambrosia: {0}".format(bool_from_state(state_text, "ambrosia")),
        "  serpent_island: {0}".format(bool_from_state(state_text, "serpent_island")),
        "  isle_of_dread: {0}".format(bool_from_state(state_text, "isle_of_dread")),
        "  underworld: {0}".format(bool_from_state(state_text, "underworld")),
        "",
        "known_gates:",
    ]

    gate_entries = [
        "Lodoria tarot pages require an account character with `the Land of Lodoria` discovered.",
        "Savage tarot page requires an account character with `the Savaged Empire` discovered.",
        "Alien tarot route is already selected through THE STAR and remains current history, not a new start option.",
        "Thieves Guild board and membership routes require actual guild membership and/or gold.",
        "Starter thief route is blocked by missing exact thief-note assignment text, no lockpick, no guild membership, and 0 gold.",
        "Paid services seen so far are not starter money routes while Mira has 0 gold.",
    ]
    for entry in gate_entries:
        list_item(lines, 2, quoted(entry))

    lines.extend(["", "npc_and_shop_outcomes:"])
    outcomes = [
        ("Donata", "Speech produced only a rumor about gem-scaled dragon-like creatures."),
        ("Tsesas", "Context-click and double-click produced no menu, paperdoll, prompt, speech, or combat."),
        ("Iain", "Thief stock and lockbox service are money-gated."),
        ("Lore", "Thieves Guild membership remains an 8000 gold blocker."),
        ("Saxon", "Survival gear talk did not provide gold, lockpicks, or a thief assignment route."),
        ("Condon", "Mage shop/service rows are goods or paid services, not a starter-money path."),
        ("Melinda", "Tinker services matter later but did not solve the current 0-gold blocker."),
        ("Rosanne", "Tinker guildmaster/lockpicking quote remains money-gated."),
        ("Dominick", "Animal trainer and stable services are paid or empty for Mira."),
    ]
    for name, outcome in outcomes:
        if name.lower() in log_text.lower() or name in state_text:
            lines.append("  - name: {0}".format(quoted(name)))
            lines.append("    outcome: {0}".format(quoted(outcome)))

    lines.extend(["", "money_tool_blockers:"])
    blockers = [
        "Mira has 0 gold in current continuity.",
        "No lockpick is available in current continuity.",
        "No Thieves Guild membership is active.",
        "The exact thief-note assignment line was not captured.",
        "Visible shop coffers remain guarded theft risk, not honest starter loot.",
    ]
    for blocker in blockers:
        list_item(lines, 2, quoted(blocker))

    lines.extend(["", "manual_capture_required:"])
    lines.append("  - id: \"thief_note_assignment_line\"")
    lines.append("    status: \"unresolved\"")
    lines.append("    reason: \"The randomized first assignment sentence was visible in a prior note gump but was not preserved exactly.\"")
    lines.append("    route_policy: \"Do not route the thief-job branch until the exact visible text is recaptured or the branch is abandoned.\"")

    lines.extend(["", "active_leads:"])
    for lead in active_leads:
        list_item(lines, 2, quoted(lead))

    lines.extend(
        [
            "",
            "map_aliases:",
            "  - marker_name: \"SavegedEmpire\"",
            "    server_map_name: \"SavagedEmpire\"",
            "    policy: \"Treat as an explicit historical marker spelling alias; do not silently rename marker files during run automation.\"",
            "",
        ]
    )

    return "\n".join(lines)


def generated_outputs() -> dict[Path, str]:
    log_text = read_text(ccwm_path("Confictura_Codex_World_Map.md"))
    state_text = read_text(ccwm_path("Simulation_State.yaml"))

    return {
        ccwm_path("generated", "Run_Index.md"): build_run_index(log_text),
        ccwm_path("generated", "Knowledge_Index.yaml"): build_knowledge_index(log_text, state_text),
    }


def check_outputs(outputs: dict[Path, str]) -> int:
    stale: List[Path] = []

    for path, content in outputs.items():
        if not path.exists() or read_text(path) != content:
            stale.append(path)

    if stale:
        for path in stale:
            print("STALE {0}".format(path))
        return 1

    print("OK generated indexes are current")
    return 0


def main(argv: Iterable[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated indexes are stale")
    args = parser.parse_args(list(argv))

    outputs = generated_outputs()

    if args.check:
        return check_outputs(outputs)

    changed = []
    for path, content in outputs.items():
        if write_if_changed(path, content):
            changed.append(path)

    if changed:
        for path in changed:
            print("WROTE {0}".format(path))
    else:
        print("OK generated indexes already current")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
